# Generated by Django 5.1.8 on 2025-04-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='translation',
            field=models.TextField(blank=True),
        ),
    ]
