"""
Django settings for subtitle_collector project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ax7%t=&q&36xj4%#237wz_u%%=6@r)!s!s$ii19afh(g5rpy!i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.2.171',
    'dejavocab.com',
    'www.dejavocab.com',
    '103.131.131.220',  # 添加您的IP地址
    'linkiai.com',      # 添加另一个域名
    'www.linkiai.com',   # 包含www子域名
    '0b55-104-234-99-10.ngrok-free.app',  # ngrok 域名
    '*.ngrok-free.app',  # 支持所有 ngrok 域名
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # Add token authentication
    'corsheaders',
    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    # 'api.middleware.SecureRedirectMiddleware',  # 已移除，由Nginx处理重定向
    'django.middleware.common.CommonMiddleware',
    # 在开发环境中禁用CSRF中间件
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 用户活动跟踪中间件 - 注意必须在AuthenticationMiddleware后面
    'api.middleware.UserActivityMiddleware',
]

ROOT_URLCONF = 'subtitle_collector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'api' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'subtitle_collector.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django REST Framework settings
REST_FRAMEWORK = {
    # 为Token认证提供最高优先级
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Token auth first
        'rest_framework.authentication.BasicAuthentication',
        # 移除SessionAuthentication以避免CSRF检查
        # 'rest_framework.authentication.SessionAuthentication', 
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://dejavocab.com",
    "https://www.dejavocab.com",
    "https://www.youtube.com",
    "http://0b55-104-234-99-10.ngrok-free.app",
    "https://0b55-104-234-99-10.ngrok-free.app"
]

# 跨域请求是否支持cookie
CORS_ALLOW_CREDENTIALS = True

# 使用正则表达式匹配所有Chrome扩展ID
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^chrome-extension://.*$",  # 匹配任何Chrome扩展
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# CSRF设置
# 允许Chrome扩展访问
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://dejavocab.com",
    "https://www.dejavocab.com",
    "http://0b55-104-234-99-10.ngrok-free.app",
    "https://0b55-104-234-99-10.ngrok-free.app"
]

# 对于Chrome扩展，我们需要在CSRF中间件中特别处理
# Django 4.0+支持在CSRF_TRUSTED_ORIGINS中使用通配符
# 但更安全的方式是在视图中使用装饰器 @csrf_exempt 或自定义中间件来处理Chrome扩展请求

# CSRF_COOKIE_SECURE = False  # 开发环境不需要HTTPS

# 配置日志
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'ignore_common_404s': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not (
                record.levelname == 'WARNING' and 
                record.getMessage().startswith(('Not Found:', '"GET /')) and
                any(path in record.getMessage() for path in [
                    # Git和Docker相关
                    '/.git', '/Dockerfile', '/.dockerignore', '/config.js',
                    
                    # API文档相关
                    '/api-docs', '/swagger', '/openapi',
                    
                    # 数据库相关
                    '/backup.sql', '/db_backup.sql', '/backup/',
                    
                    # Laravel相关
                    '/storage/framework/', '/storage/logs/', '/.env', 'env.php', 'local.xml',
                    
                    # Drupal和WordPress相关
                    '/sites/all/', '/core/install.php', '/CHANGELOG.txt', '/wp-', '/xmlrpc.php',
                    
                    # Symfony相关
                    '/config/packages/', '/config/routes', '/web/config.php', '/web.config',
                    
                    # Node.js相关
                    '/package.json', '/yarn.lock', '/.npmrc', '/server.js', '/app.js',
                    
                    # 日志文件相关
                    '/var/log', '/logs/', '/debug.log', '/error',
                    
                    # 配置文件相关
                    '/.htaccess', '/configuration.php', '/.well-known/'
                ])
            )
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['ignore_common_404s'],
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
            'filters': ['ignore_common_404s'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
            'filters': ['ignore_common_404s'],
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
            'filters': ['ignore_common_404s'],
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 增加请求字段数量限制以处理大量字幕
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
